---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xicologrise/wiki.xico.logrise.pt/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R dev $DEPLOYPATH
    - /bin/cp -R lang $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp -R themes $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp bookstack-system-cli $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp crowdin.yml $DEPLOYPATH
    - cd $DEPLOYPATH && composer install --no-dev
    - cd $DEPLOYPATH && php artisan migrate
    - cd $DEPLOYPATH && php artisan cache:clear
    - cd $DEPLOYPATH && php artisan config:clear
    - cd $DEPLOYPATH && php artisan view:clear